### ISSUE TITLE
Arduino Connection

### ISSUE THREAD

**Issue by oanciufri** [sgofferj/EDIPTFT#3]
Hello,

Thank you for your amazing work. 

I am trying to connect a eDIP240B-7LW to a Arduino Mega via SPI and it seems that I can't figure it out for the past few days. I would appreciate if you could share a wiring diagram and, perhaps, a working sketch for me to start learning. 

Thank you!

Regards,
Horia

**Comment by sgofferj** [comment]
The library currently only supports serial communication. I can't help you with SPI, unfortunately. A code example is at the end of Readme.md.

**Comment by oanciufri** [comment]
Thanks!
